# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('delivery_method', models.PositiveSmallIntegerField(choices=[(1, 'SMS'), (2, 'Voice'), (3, 'E-Mail')])),
                ('token', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('destination', models.CharField(max_length=128)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'In Progress'), (3, 'Complete'), (4, 'Failed'), (5, 'Expired')], default=1)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='tenants.Integration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
