# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 23:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('tenants', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices',
                                    to='tenants.Client'),
        ),
        migrations.AddField(
            model_name='device',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.Enrollment'),
        ),
        migrations.AddField(
            model_name='device',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices',
                                    to='devices.DeviceKind'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('name', 'client')]),
        ),
    ]
