# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='uid',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
