# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('configuration',
                 django.contrib.postgres.fields.jsonb.JSONField(
                     blank=True, null=True)),
            ], ),
    ]
