# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 23:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('devices', '0002_auto_20170826_2332'),
        ('tenants', '0001_initial'),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='binding_context',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='enrollments',
                to='tenants.BindingContext'), ),
        migrations.AddField(
            model_name='enrollment',
            name='client',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='enrollment',
                to='tenants.Client'), ),
        migrations.AddField(
            model_name='enrollment',
            name='device_selection',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='enrollment',
                to='devices.DeviceSelection'), ),
        migrations.AddField(
            model_name='enrollment',
            name='integration',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='enrollments',
                to='tenants.Integration'), ),
        migrations.AddField(
            model_name='enrollment',
            name='policy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='enrollments',
                to='policy.Policy'), ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(
                fields=['integration', 'username'],
                name='enrollment__integra_3c1edd_idx'), ),
    ]
