# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('devices', '0002_auto_20170121_2259'),
        ('tenants', '0001_initial'),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='binding_context',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenants.BindingContext'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='tenants.Client'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='device_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='devices.DeviceSelection'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenants.Integration'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='policy.Policy'),
        ),
    ]
