# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Token Digits Length'), (2, 'Challenge Expiration (Minutes)'), (3, 'Enrollment Expiration (Minutes)')]),
        ),
    ]
