# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 23:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.PositiveSmallIntegerField(
                    choices=[(1, 'New'), (2, 'In Progress'), (3, 'Complete'), (4, 'Failed'), (5, 'Expired')],
                    default=1)),
                ('private_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('public_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=128, null=True)),
                ('expires_at', models.DateTimeField()),
                ('portal_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
