# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20170121_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='portal_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
